"""symfony_lock.py - S170a: the Lua scripts of Symfony's Lock component
(src/Symfony/Component/Lock/Store/RedisStore.php), exactly as Symfony 5.4
through 7.4 send them - the TIME variant and the ARGV variant of each - so
test/symlocktest.sh can load them by body and run them by SHA1.  perfcached
does not run these: it recognises them by SHA1 and runs its own C.

The script text is Symfony's:
Copyright (c) 2004-present Fabien Potencier
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions: The above copyright
notice and this permission notice shall be included in all copies or
substantial portions of the Software.  THE SOFTWARE IS PROVIDED "AS IS",
WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.
"""
import hashlib

BODIES = {
    'probe': "\n                local now = redis.call(\"TIME\")\n                redis.call(\"SET\", KEYS[1], \"1\", \"PX\", 1)\n\n\t            return 1\n            ",
    'save': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n            local ttl = tonumber(ARGV[3])\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n                local now = redis.call(\"TIME\")\n                now = now[1] * 1000 + math.floor(now[2] / 1000)\n            \n\n            -- Remove expired values\n            redis.call(\"ZREMRANGEBYSCORE\", key, \"-inf\", now)\n\n            -- is already acquired\n            if redis.call(\"ZSCORE\", key, uniqueToken) then\n                -- is not WRITE lock and cannot be promoted\n                if not redis.call(\"ZSCORE\", key, \"__write__\") and redis.call(\"ZCOUNT\", key, \"-inf\", \"+inf\") > 1  then\n                    return false\n                end\n            elseif redis.call(\"ZCOUNT\", key, \"-inf\", \"+inf\") > 0  then\n                return false\n            end\n\n            redis.call(\"ZADD\", key, now + ttl, uniqueToken)\n            redis.call(\"ZADD\", key, now + ttl, \"__write__\")\n\n            -- Extend the TTL of the key\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            redis.call(\"PEXPIREAT\", key, maxExpiration)\n\n            return true\n        ",
    'save_argv': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n            local ttl = tonumber(ARGV[3])\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n            local now = tonumber(ARGV[1])\n            now = math.floor(now * 1000)\n        \n\n            -- Remove expired values\n            redis.call(\"ZREMRANGEBYSCORE\", key, \"-inf\", now)\n\n            -- is already acquired\n            if redis.call(\"ZSCORE\", key, uniqueToken) then\n                -- is not WRITE lock and cannot be promoted\n                if not redis.call(\"ZSCORE\", key, \"__write__\") and redis.call(\"ZCOUNT\", key, \"-inf\", \"+inf\") > 1  then\n                    return false\n                end\n            elseif redis.call(\"ZCOUNT\", key, \"-inf\", \"+inf\") > 0  then\n                return false\n            end\n\n            redis.call(\"ZADD\", key, now + ttl, uniqueToken)\n            redis.call(\"ZADD\", key, now + ttl, \"__write__\")\n\n            -- Extend the TTL of the key\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            redis.call(\"PEXPIREAT\", key, maxExpiration)\n\n            return true\n        ",
    'read': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n            local ttl = tonumber(ARGV[3])\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n                local now = redis.call(\"TIME\")\n                now = now[1] * 1000 + math.floor(now[2] / 1000)\n            \n\n            -- Remove expired values\n            redis.call(\"ZREMRANGEBYSCORE\", key, \"-inf\", now)\n\n            -- lock not already acquired and a WRITE lock exists?\n            if not redis.call(\"ZSCORE\", key, uniqueToken) and redis.call(\"ZSCORE\", key, \"__write__\") then\n                return false\n            end\n\n            redis.call(\"ZADD\", key, now + ttl, uniqueToken)\n            redis.call(\"ZREM\", key, \"__write__\")\n\n            -- Extend the TTL of the key\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            redis.call(\"PEXPIREAT\", key, maxExpiration)\n\n            return true\n        ",
    'read_argv': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n            local ttl = tonumber(ARGV[3])\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n            local now = tonumber(ARGV[1])\n            now = math.floor(now * 1000)\n        \n\n            -- Remove expired values\n            redis.call(\"ZREMRANGEBYSCORE\", key, \"-inf\", now)\n\n            -- lock not already acquired and a WRITE lock exists?\n            if not redis.call(\"ZSCORE\", key, uniqueToken) and redis.call(\"ZSCORE\", key, \"__write__\") then\n                return false\n            end\n\n            redis.call(\"ZADD\", key, now + ttl, uniqueToken)\n            redis.call(\"ZREM\", key, \"__write__\")\n\n            -- Extend the TTL of the key\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            redis.call(\"PEXPIREAT\", key, maxExpiration)\n\n            return true\n        ",
    'refresh': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n            local ttl = tonumber(ARGV[3])\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n                local now = redis.call(\"TIME\")\n                now = now[1] * 1000 + math.floor(now[2] / 1000)\n            \n\n            -- lock already acquired acquired?\n            if not redis.call(\"ZSCORE\", key, uniqueToken) then\n                return false\n            end\n\n            redis.call(\"ZADD\", key, now + ttl, uniqueToken)\n            -- if the lock is also a WRITE lock, increase the TTL\n            if redis.call(\"ZSCORE\", key, \"__write__\") then\n                redis.call(\"ZADD\", key, now + ttl, \"__write__\")\n            end\n\n            -- Extend the TTL of the key\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            redis.call(\"PEXPIREAT\", key, maxExpiration)\n\n            return true\n        ",
    'refresh_argv': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n            local ttl = tonumber(ARGV[3])\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n            local now = tonumber(ARGV[1])\n            now = math.floor(now * 1000)\n        \n\n            -- lock already acquired acquired?\n            if not redis.call(\"ZSCORE\", key, uniqueToken) then\n                return false\n            end\n\n            redis.call(\"ZADD\", key, now + ttl, uniqueToken)\n            -- if the lock is also a WRITE lock, increase the TTL\n            if redis.call(\"ZSCORE\", key, \"__write__\") then\n                redis.call(\"ZADD\", key, now + ttl, \"__write__\")\n            end\n\n            -- Extend the TTL of the key\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            redis.call(\"PEXPIREAT\", key, maxExpiration)\n\n            return true\n        ",
    'exists': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n                local now = redis.call(\"TIME\")\n                now = now[1] * 1000 + math.floor(now[2] / 1000)\n            \n\n            -- Remove expired values\n            redis.call(\"ZREMRANGEBYSCORE\", key, \"-inf\", now)\n\n            if redis.call(\"ZSCORE\", key, uniqueToken) then\n                return true\n            end\n\n            return false\n        ",
    'exists_argv': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[2]\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            \n            local now = tonumber(ARGV[1])\n            now = math.floor(now * 1000)\n        \n\n            -- Remove expired values\n            redis.call(\"ZREMRANGEBYSCORE\", key, \"-inf\", now)\n\n            if redis.call(\"ZSCORE\", key, uniqueToken) then\n                return true\n            end\n\n            return false\n        ",
    'release': "\n            local key = KEYS[1]\n            local uniqueToken = ARGV[1]\n\n            -- asserts the KEY is compatible with current version (old Symfony <5.2 BC)\n            if redis.call(\"TYPE\", key).ok == \"string\" then\n                return false\n            end\n\n            -- lock not already acquired\n            if not redis.call(\"ZSCORE\", key, uniqueToken) then\n                return false\n            end\n\n            redis.call(\"ZREM\", key, uniqueToken)\n            redis.call(\"ZREM\", key, \"__write__\")\n\n            local maxExpiration = redis.call(\"ZREVRANGE\", key, 0, 0, \"WITHSCORES\")[2]\n            if nil ~= maxExpiration then\n                redis.call(\"PEXPIREAT\", key, maxExpiration)\n            end\n\n            return true\n        ",
}
SHA = {k: hashlib.sha1(v.encode()).hexdigest() for k, v in BODIES.items()}
