/* SPDX-License-Identifier: GPL-2.0-or-later
 * Copyright (c) 2026 Yury Kirsanov - see COPYING */
/* statuspage.c - GENERATED-SHAPED but hand-maintained: the S37
 * page as one C string.  Edit it here; there is no build step and
 * no asset to fetch, which is the point (see statuspage.h). */
#include "statuspage.h"

const char pc_status_page[] =
	"<!doctype html><meta charset=utf-8>\n"
	"<title>perfcached</title>\n"
	"<meta name=viewport content=\"width=device-width,initial-scale=1\">\n"
	"<style>\n"
	":root{--bg:#12141a;--fg:#e6e8ee;--dim:#9aa1b1;--line:#262a35;--card:#181b23;\n"
	"--ok:#4ec9a0;--warn:#e2b341;--bad:#e06c75;--self:#5aa9e6}\n"
	"*{box-sizing:border-box}\n"
	"body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.5 ui-monospace,\n"
	"SFMono-Regular,Menlo,Consolas,monospace}\n"
	"header{padding:18px 22px;border-bottom:1px solid var(--line);display:flex;\n"
	"gap:16px;align-items:baseline;flex-wrap:wrap}\n"
	"h1{font-size:15px;margin:0;letter-spacing:.08em;text-transform:uppercase}\n"
	".meta{color:var(--dim);font-size:12px}\n"
	"main{padding:22px;max-width:1100px}\n"
	".vantage{color:var(--dim);font-size:12px;margin:0 0 14px}\n"
	"table{border-collapse:collapse;width:100%}\n"
	"th{text-align:left;font-weight:400;color:var(--dim);font-size:11px;\n"
	"text-transform:uppercase;letter-spacing:.06em;padding:0 12px 8px 0;\n"
	"border-bottom:1px solid var(--line)}\n"
	"td{padding:9px 12px 9px 0;border-bottom:1px solid var(--line);\n"
	"white-space:nowrap}\n"
	"tr.self td{background:rgba(90,169,230,.07)}\n"
	".role{font-size:11px;padding:2px 7px;border-radius:3px;border:1px solid}\n"
	".master{color:var(--ok);border-color:rgba(78,201,160,.4)}\n"
	".backup{color:var(--warn);border-color:rgba(226,179,65,.4)}\n"
	".member{color:var(--dim);border-color:var(--line)}\n"
	".you{color:var(--self);font-size:11px;margin-left:6px}\n"
	".bar{display:inline-block;width:120px;height:6px;background:var(--line);\n"
	"border-radius:3px;overflow:hidden;vertical-align:middle;margin-right:8px}\n"
	".bar>i{display:block;height:100%;background:var(--ok)}\n"
	".bar.warn>i{background:var(--warn)}.bar.bad>i{background:var(--bad)}\n"
	/* A node's STATE is the thing an operator scans this table for, and
	 * it read as plain grey text whatever it said - "failed" looked
	 * exactly like "ready".  Colour it, and make failed the loudest
	 * thing on the page: it means that node is out of selection and
	 * needs a human. */
	".st{font-weight:600}\n"
	".st-ready{color:var(--ok)}\n"
	".st-recovering,.st-draining{color:var(--warn)}\n"
	".st-failed{color:var(--bad);background:rgba(224,108,117,.12);\n"
	"  border:1px solid rgba(224,108,117,.45);border-radius:4px;\n"
	"  padding:1px 7px;letter-spacing:.02em}\n"
	".err{color:var(--bad);padding:14px 0}\n"
	"footer{color:var(--dim);font-size:11px;padding:0 22px 24px}\n"
	"</style>\n"
	"<header>\n"
	"  <h1>perfcached</h1>\n"
	"  <span class=meta id=node></span>\n"
	"  <span class=meta id=age></span>\n"
	"</header>\n"
	"<main>\n"
	"  <p class=vantage>The fleet <b>as this node sees it</b>. Every node\n"
	"  serves its own view: if two nodes disagree about the membership, that\n"
	"  disagreement is a partition and this is where you see it.</p>\n"
	"  <div id=body><p class=meta>loading…</p></div>\n"
	"</main>\n"
	"<footer id=foot></footer>\n"
	"<script>\n"
	"var last = 0;\n"
	"function pct(u,t){ return t ? Math.round(100*u/t) : 0; }\n"
	"function esc(s){ return String(s).replace(/[&<>\"]/g,\n"
	"  function(c){ return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]; }); }\n"
	"function draw(d){\n"
	"  var m = d.members || [], self = null, i, h;\n"
	"  for (i = 0; i < m.length; i++) if (m[i].self) self = m[i];\n"
	"  document.getElementById('node').textContent =\n"
	"    (self ? 'node ' + self.node + ' · ' + self.addr : 'unclustered') +\n"
	"    ' · ' + m.length + ' member' + (m.length === 1 ? '' : 's');\n"
	"  h = '<table><tr><th>node</th><th>address</th><th>role</th>' +\n"
	"      '<th>state</th><th>headroom</th></tr>';\n"
	"  for (i = 0; i < m.length; i++) {\n"
	"    var n = m[i], cls = n.master ? 'master' : n.backup ? 'backup' : 'member',\n"
	"        hp = n.headroom_pct, bar = '', bc = hp < 10 ? 'bad' : hp < 25 ? 'warn' : '';\n"
	"    if (hp !== undefined)\n"
	"      bar = '<span class=\"bar ' + bc + '\"><i style=\"width:' + hp +\n"
	"            '%\"></i></span>' + hp + '%';\n"
	"    h += '<tr class=\"' + (n.self ? 'self' : '') + '\"><td>' + esc(n.node) +\n"
	"      (n.self ? '<span class=you>this node</span>' : '') + '</td><td>' +\n"
	"      esc(n.addr) + ':' + esc(n.port) + '</td><td><span class=\"role ' + cls +\n"
	"      '\">' + cls + '</span></td><td><span class=\"st st-' +\n"
	"      esc(String(n.state || '')).replace(/[^a-z]/g, '') + '\">' +\n"
	"      esc(n.state || '-') + '</span></td><td>' +\n"
	"      (bar || '<span class=meta>-</span>') + '</td></tr>';\n"
	"  }\n"
	"  document.getElementById('body').innerHTML = h + '</table>';\n"
	"  document.getElementById('foot').textContent =\n"
	"    'read-only · refreshes every 3s · no data can be changed here';\n"
	"}\n"
	"function tick(){\n"
	"  var x = new XMLHttpRequest();\n"
	"  x.open('GET', 'members', true);\n"
	"  x.onreadystatechange = function(){\n"
	"    if (x.readyState !== 4) return;\n"
	"    if (x.status === 200) {\n"
	"      try { draw(JSON.parse(x.responseText)); last = Date.now(); }\n"
	"      catch (e) { document.getElementById('body').innerHTML =\n"
	"        '<p class=err>malformed reply</p>'; }\n"
	"    } else {\n"
	"      document.getElementById('body').innerHTML =\n"
	"        '<p class=err>this node did not answer (HTTP ' + x.status + ')</p>';\n"
	"    }\n"
	"  };\n"
	"  x.send();\n"
	"}\n"
	"setInterval(function(){\n"
	"  document.getElementById('age').textContent =\n"
	"    last ? 'updated ' + Math.round((Date.now()-last)/1000) + 's ago' : '';\n"
	"}, 1000);\n"
	"tick(); setInterval(tick, 3000);\n"
	"</script>\n"
	"\n"
	;
const unsigned int pc_status_page_len = sizeof pc_status_page - 1;
